
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsgiwomqpovjxokruduc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZ2l3b21xcG92anhva3J1ZHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTUzNTMsImV4cCI6MjA2MjE5MTM1M30.tczwtV941t7ikp7c_afBkGejHVYtS1bKDRJ2tBoCQcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export types from the types file
export type { Database } from './types';
